using UnityEngine;

/// <summary>
/// Drives the player's walk animation directly from a sliced sprite sheet.
///
/// Why not an Animator/AnimationClip setup? Because the sheet is generated by
/// Tools/GenArt.py and sliced by Tools' editor step; keeping the frames as a
/// plain Sprite[] means there is no .controller asset to keep in sync and the
/// animation cannot silently break if a clip is reimported.
///
/// `frames` is laid out as [direction * framesPerDirection + frame], where
/// direction is 0 = Down, 1 = Left, 2 = Right, 3 = Up.
/// </summary>
[RequireComponent(typeof(SpriteRenderer))]
public class PlayerAnimator : MonoBehaviour
{
    [Header("Frames")]
    [Tooltip("16 entries: 4 rows (Down,Left,Right,Up) x 4 walk frames.")]
    public Sprite[] frames = new Sprite[0];
    public int framesPerDirection = 4;

    [Header("Idle")]
    [Tooltip("Which frame index to hold while standing still.")]
    public int idleFrame = 0;

    [Header("Timing")]
    [Tooltip("Walk frames per second.")]
    public float walkFps = 8f;
    [Tooltip("Extra playback speed while running.")]
    public float runFpsMultiplier = 1.5f;

    [Header("Bobbing (optional)")]
    [Tooltip("Vertical bob amplitude in world units while walking. 0 disables.")]
    public float bobAmplitude = 0f;
    public float bobFps = 8f;

    private SpriteRenderer spriteRenderer;
    private PlayerController controller;
    private int direction;
    private float timer;
    private int frame;
    private Vector3 baseLocalPosition;

    void Awake()
    {
        spriteRenderer = GetComponent<SpriteRenderer>();
        controller = GetComponentInParent<PlayerController>();
        if (controller == null)
            controller = PlayerController.Instance;
        baseLocalPosition = transform.localPosition;
    }

    void LateUpdate()
    {
        if (spriteRenderer == null)
            return;

        if (controller != null)
            direction = Mathf.Clamp(controller.FacingIndex, 0, 3);

        bool moving = controller != null && controller.IsMoving;
        bool running = Input.GetKey(KeyCode.LeftShift) || Input.GetKey(KeyCode.RightShift);
        float fps = Mathf.Max(0.01f, walkFps * (running ? runFpsMultiplier : 1f));

        if (moving && framesPerDirection > 0)
        {
            timer += Time.deltaTime * fps;
            int span = Mathf.Max(1, framesPerDirection);
            while (timer >= 1f)
            {
                timer -= 1f;
                frame = (frame + 1) % span;
            }
        }
        else
        {
            timer = 0f;
            frame = Mathf.Clamp(idleFrame, 0, Mathf.Max(0, framesPerDirection - 1));
        }

        ApplySprite();

        if (bobAmplitude > 0f)
        {
            float phase = moving
                ? Mathf.Abs(Mathf.Sin(Time.time * bobFps * Mathf.PI)) * bobAmplitude
                : 0f;
            transform.localPosition = baseLocalPosition + new Vector3(0f, phase, 0f);
        }
    }

    private void ApplySprite()
    {
        if (frames == null || frames.Length == 0)
            return;

        int index = direction * Mathf.Max(1, framesPerDirection) + frame;
        if (index < 0 || index >= frames.Length)
            index = Mathf.Clamp(index, 0, frames.Length - 1);

        Sprite wanted = frames[index];
        if (wanted != null && spriteRenderer.sprite != wanted)
            spriteRenderer.sprite = wanted;
    }

    /// <summary>Assign a whole sheet's frames at once (used by the editor builder).</summary>
    public void SetFrames(Sprite[] newFrames, int perDirection)
    {
        frames = newFrames;
        framesPerDirection = Mathf.Max(1, perDirection);
    }
}